// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyncRoutineWS.PCNWModel;

public partial class ProjAo
{
    public int ProjAo1 { get; set; }

    public int? AotypeId { get; set; }

    public int? ArchOwnerId { get; set; }

    public bool? BoldBp { get; set; }

    public bool? ShowOnResults { get; set; }

    public int? ProjId { get; set; }

    public int? SortOrder { get; set; }

    public int SyncStatus { get; set; }

    public int? SyncProjAoid { get; set; }

    public virtual ArchOwner ArchOwner { get; set; }

    public virtual Project Proj { get; set; }
}