// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SyncRoutineWS.OCPCModel;
[Table("tblAOType")]
public partial class TblAOType
{
    [Key]
    public int AOTypeID { get; set; }
    public string AOType { get; set; }
    public bool Owner { get; set; }
}