// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyncRoutineWS.OCPCModel;

public partial class TblAddendum
{
    public int AddendaId { get; set; }

    public string AddendaNo { get; set; }

    public bool? MoreInfo { get; set; }

    public int? ProjId { get; set; }

    public DateTime? InsertDt { get; set; }

    public string MvwebPath { get; set; }

    public DateTime? IssueDt { get; set; }

    public string PageCnt { get; set; }

    public bool? NewBd { get; set; }

    public int SyncStatus { get; set; }

    public virtual TblProject Proj { get; set; }
}