// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyncRoutineWS.OCPCModel;

public partial class TblContractor
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Addr1 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public int? Type2 { get; set; }

    public int? ConTypeId { get; set; }

    public string Email { get; set; }

    public string Uid { get; set; }

    public string Pwd { get; set; }

    public string WebAddress { get; set; }

    public string Cnote { get; set; }

    public bool? Hosting { get; set; }

    public string HostingPwd { get; set; }

    public DateTime? GcserviceTimeStamp { get; set; }

    public bool? NoFax { get; set; }

    public int SyncStatus { get; set; }

    public virtual ICollection<TblProjCon> TblProjCons { get; set; } = new List<TblProjCon>();
}