// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyncRoutineWS.OCPCModel;

public partial class TblProjCon
{
    public int ProjConId { get; set; }

    public int? ConId { get; set; }

    public int? ConTypeId { get; set; }

    public decimal? BidAmt { get; set; }

    public string Rank { get; set; }

    public bool? AwardedTo { get; set; }

    public bool? Apparent { get; set; }

    public bool? IssuingOffice { get; set; }

    public bool SubBid { get; set; }

    public string Ucpwd { get; set; }

    public string PrivatePwd { get; set; }

    public bool? HostingPublic { get; set; }

    public string HostingDateExtention { get; set; }

    public string Note { get; set; }

    public int? ProjId { get; set; }

    /// <summary>
    /// This controls what tblProjects BidDt they will be using
    /// </summary>
    public string SortOrder { get; set; }

    public int? BidDt { get; set; }

    public bool? Bidding { get; set; }

    public bool? Lm { get; set; }

    public bool? NotBidding { get; set; }

    public string Person { get; set; }

    public DateTime? TimeStamp { get; set; }

    public int SyncStatus { get; set; }

    public virtual TblContractor Con { get; set; }

    public virtual TblProject Proj { get; set; }
}